### PR TITLE
Fix typo in readme instructions

### PR DESCRIPTION
**Pull request by vakila**
Fixes a teeny typo, missing "auth" in `npx convex auth add`

### CODE REVIEW

**Review by nipunn1313 — APPROVED** [review]

**Review by nipunn1313 — CHANGES_REQUESTED** [review]
wait actually

**Comment by nipunn1313** [comment]
This repo is generated out of our internal main repo. I think you will have to update the corresponding file in `get-convex/convex` (in `npm-packages/demos`)

**Comment by vakila** [comment]
Ah gotchya, unfortunately I don't have access to that so I will have to let someone on the team make the fix! Will close this one out then, thanks!

**Comment by nipunn1313** [comment]
I got it!

**Pull request closed without merging**
